"""Initial migration with all models

Revision ID: 483e7f9c5d31
Revises: 
Create Date: 2026-04-26 10:11:49.813533

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '483e7f9c5d31'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_moderator_messages_id', table_name='moderator_messages')
    op.drop_index('ix_moderator_messages_report_id', table_name='moderator_messages')
    op.drop_table('moderator_messages')
    op.drop_index('ix_contact_messages_id', table_name='contact_messages')
    op.drop_table('contact_messages')
    op.drop_index('ix_reports_category', table_name='reports')
    op.drop_index('ix_reports_id', table_name='reports')
    op.drop_index('ix_reports_region', table_name='reports')
    op.drop_index('ix_reports_status', table_name='reports')
    op.drop_index('ix_reports_tracking_id', table_name='reports')
    op.drop_table('reports')
    op.drop_index('ix_timeline_events_id', table_name='timeline_events')
    op.drop_index('ix_timeline_events_report_id', table_name='timeline_events')
    op.drop_table('timeline_events')
    op.drop_index('ix_evidence_files_id', table_name='evidence_files')
    op.drop_index('ix_evidence_files_report_id', table_name='evidence_files')
    op.drop_index('ix_evidence_files_sha256', table_name='evidence_files')
    op.drop_table('evidence_files')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('evidence_files',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('report_id', sa.INTEGER(), nullable=False),
    sa.Column('original_name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('stored_name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('content_type', sa.VARCHAR(length=128), nullable=True),
    sa.Column('size_bytes', sa.INTEGER(), nullable=False),
    sa.Column('sha256', sa.VARCHAR(length=64), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_evidence_files_sha256', 'evidence_files', ['sha256'], unique=False)
    op.create_index('ix_evidence_files_report_id', 'evidence_files', ['report_id'], unique=False)
    op.create_index('ix_evidence_files_id', 'evidence_files', ['id'], unique=False)
    op.create_table('timeline_events',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('report_id', sa.INTEGER(), nullable=False),
    sa.Column('status', sa.VARCHAR(length=64), nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_timeline_events_report_id', 'timeline_events', ['report_id'], unique=False)
    op.create_index('ix_timeline_events_id', 'timeline_events', ['id'], unique=False)
    op.create_table('reports',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('tracking_id', sa.VARCHAR(length=32), nullable=False),
    sa.Column('category', sa.VARCHAR(length=64), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=False),
    sa.Column('location', sa.VARCHAR(length=255), nullable=True),
    sa.Column('region', sa.VARCHAR(length=80), nullable=True),
    sa.Column('organization', sa.VARCHAR(length=255), nullable=True),
    sa.Column('incident_date', sa.VARCHAR(length=32), nullable=True),
    sa.Column('anonymous', sa.BOOLEAN(), nullable=False),
    sa.Column('danger_flag', sa.BOOLEAN(), nullable=False),
    sa.Column('contact', sa.VARCHAR(length=255), nullable=True),
    sa.Column('status', sa.VARCHAR(length=64), nullable=False),
    sa.Column('ai_score', sa.INTEGER(), nullable=False),
    sa.Column('ai_result', sa.TEXT(), nullable=True),
    sa.Column('reward_status', sa.VARCHAR(length=64), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_reports_tracking_id', 'reports', ['tracking_id'], unique=1)
    op.create_index('ix_reports_status', 'reports', ['status'], unique=False)
    op.create_index('ix_reports_region', 'reports', ['region'], unique=False)
    op.create_index('ix_reports_id', 'reports', ['id'], unique=False)
    op.create_index('ix_reports_category', 'reports', ['category'], unique=False)
    op.create_table('contact_messages',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), nullable=True),
    sa.Column('email', sa.VARCHAR(length=255), nullable=False),
    sa.Column('question_type', sa.VARCHAR(length=80), nullable=False),
    sa.Column('message', sa.TEXT(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_contact_messages_id', 'contact_messages', ['id'], unique=False)
    op.create_table('moderator_messages',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('report_id', sa.INTEGER(), nullable=False),
    sa.Column('sender', sa.VARCHAR(length=64), nullable=False),
    sa.Column('message', sa.TEXT(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_moderator_messages_report_id', 'moderator_messages', ['report_id'], unique=False)
    op.create_index('ix_moderator_messages_id', 'moderator_messages', ['id'], unique=False)
    # ### end Alembic commands ###
